name = "svg2png-worker"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
workers_dev = true
compatibility_date = "2021-08-27" # required
compatibility_flags = [ "formdata_parser_supports_files" ] # required

[build]
command = "npm run build"

[build.upload]
dir = "dist"
format = "modules"
main = "./index.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[[build.upload.rules]]
globs = ["**/*.ttf"]
type = "Data"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
